<LitterBoxWidget>:
    pos: 500, 50
    size: 150, 150
    
    Image:
    	source: "LitterBox.png"
    	pos: root.pos
    	
    Label:
    	#text: str(root.DisplayLitter)
    	text: ("%d/%d" % (root._LitterCount, root._MaxLitter))
    	#text: str(root._LitterCount) + "/" + str(root._MaxLitter)
        #text: ("%s/%s" % (str(root._LitterCount), str(root._MaxLitter)))
		pos: (root.center_x, root.center_y)
     